const Map<String, String> arSA = {
  // General
  'app_name': 'وصال',
  'ok': 'موافق',
  'cancel': 'إلغاء',
  'save': 'حفظ',
  'delete': 'حذف',
  'edit': 'تعديل',
  'done': 'تم',
  'loading': 'جاري التحميل...',
  'error': 'خطأ',
  'success': 'نجاح',
  'warning': 'تحذير',
  'yes': 'نعم',
  'no': 'لا',
  'close': 'إغلاق',
  'back': 'رجوع',
  'next': 'التالي',
  'retry': 'إعادة المحاولة',
  'search': 'بحث',
  'search_hint': 'بحث...',

  // Theme
  'theme': 'المظهر',
  'dark': 'داكن',
  'light': 'فاتح',
  'system': 'النظام',
  'dark_mode': 'الوضع الداكن',
  'light_mode': 'الوضع الفاتح',
  'system_mode': 'إعدادات النظام',

  // Language
  'language': 'اللغة',
  'english': 'الإنجليزية',
  'arabic': 'العربية',
  'select_language': 'اختر اللغة',

  // Authentication
  'login': 'تسجيل الدخول',
  'logout': 'تسجيل الخروج',
  'sign_up': 'إنشاء حساب',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'confirm_password': 'تأكيد كلمة المرور',
  'forgot_password': 'نسيت كلمة المرور؟',
  'reset_password': 'إعادة تعيين كلمة المرور',
  'create_account': 'إنشاء حساب',
  'already_have_account': 'لديك حساب بالفعل؟',
  'dont_have_account': 'ليس لديك حساب؟',
  'enter_email': 'أدخل بريدك الإلكتروني',
  'enter_password': 'أدخل كلمة المرور',
  'enter_name': 'أدخل اسمك',
  'invalid_email': 'عنوان بريد إلكتروني غير صالح',
  'password_too_short': 'كلمة المرور قصيرة جداً',
  'passwords_not_match': 'كلمات المرور غير متطابقة',
  'login_success': 'تم تسجيل الدخول بنجاح',
  'signup_success': 'تم إنشاء الحساب بنجاح',
  'logout_confirm': 'هل أنت متأكد من تسجيل الخروج؟',
  'email_verified': 'تم التحقق من بريدك الإلكتروني!',
  'check_email': 'يرجى التحقق من بريدك الإلكتروني',

  // Profile
  'profile': 'الملف الشخصي',
  'edit_profile': 'تعديل الملف الشخصي',
  'name': 'الاسم',
  'username': 'اسم المستخدم',
  'bio': 'نبذة',
  'phone': 'الهاتف',
  'change_photo': 'تغيير الصورة',
  'update_profile': 'تحديث الملف الشخصي',
  'profile_updated': 'تم تحديث الملف الشخصي بنجاح',

  // Settings
  'settings': 'الإعدادات',
  'general': 'عام',
  'notifications': 'الإشعارات',
  'privacy': 'الخصوصية',
  'about': 'حول',
  'help': 'المساعدة',
  'appearance': 'المظهر',

  // Chat
  'chats': 'المحادثات',
  'messages': 'الرسائل',
  'new_message': 'رسالة جديدة',
  'type_message': 'اكتب رسالة...',
  'send': 'إرسال',
  'delivered': 'تم التوصيل',
  'read': 'مقروءة',
  'online': 'متصل',
  'offline': 'غير متصل',
  'typing': 'يكتب...',
  'last_seen': 'آخر ظهور',
  'delete_message': 'حذف الرسالة',
  'edit_message': 'تعديل الرسالة',
  'copy_message': 'نسخ',
  'reply': 'رد',
  'forward': 'إعادة توجيه',
  'delete_for_me': 'حذف لي فقط',
  'delete_for_everyone': 'حذف للجميع',
  'message_deleted': 'تم حذف هذه الرسالة',
  'no_messages': 'لا توجد رسائل بعد',
  'start_conversation': 'ابدأ محادثة',
  'pin_message': 'تثبيت الرسالة',
  'unpin_message': 'إلغاء التثبيت',
  'pinned_messages': 'الرسائل المثبتة',

  // Contacts
  'contacts': 'جهات الاتصال',
  'add_contact': 'إضافة جهة اتصال',
  'new_contact': 'جهة اتصال جديدة',
  'add_new_contact': 'إضافة صديق جديد',
  'search_contacts': 'بحث في جهات الاتصال...',
  'contacts_on_app': 'جهات الاتصال على وصال',
  'no_contacts': 'لا توجد جهات اتصال بعد',
  'invite_friends': 'قم بدعوة أصدقائك للتطبيق',
  'saved_contacts': 'جهات الاتصال المحفوظة',
  'contact_saved': 'تم حفظ جهة الاتصال',
  'contact_deleted': 'تم حذف جهة الاتصال',
  'hey_there': 'مرحباً!',
  'you': 'أنت',
  'user': 'مستخدم',
  'add': 'إضافة',
  'login_required': 'يجب تسجيل الدخول أولاً',

  // Groups
  'groups': 'المجموعات',
  'create_group': 'إنشاء مجموعة',
  'new_group': 'مجموعة جديدة',
  'create_new_group': 'إنشاء مجموعة مع أصدقائك',
  'group_name': 'اسم المجموعة',
  'add_members': 'إضافة أعضاء',
  'members': 'الأعضاء',
  'leave_group': 'مغادرة المجموعة',
  'admin': 'مدير',
  'no_groups': 'لا توجد مجموعات بعد',

  // Calls
  'calls': 'المكالمات',
  'voice_call': 'مكالمة صوتية',
  'video_call': 'مكالمة فيديو',
  'incoming_call': 'مكالمة واردة',
  'outgoing_call': 'مكالمة صادرة',
  'missed_call': 'مكالمة فائتة',
  'call_ended': 'انتهت المكالمة',
  'calling': 'جاري الاتصال...',
  'no_calls': 'لا توجد مكالمات بعد',

  // Media
  'camera': 'الكاميرا',
  'gallery': 'المعرض',
  'document': 'مستند',
  'audio': 'صوت',
  'video': 'فيديو',
  'image': 'صورة',
  'file': 'ملف',
  'location': 'الموقع',
  'share_location': 'مشاركة الموقع',

  // Errors
  'connection_error': 'خطأ في الاتصال',
  'no_internet': 'لا يوجد اتصال بالإنترنت',
  'something_went_wrong': 'حدث خطأ ما',
  'try_again': 'يرجى المحاولة مرة أخرى',
  'session_expired': 'انتهت صلاحية الجلسة',
  'permission_denied': 'تم رفض الإذن',

  // Welcome
  'welcome': 'مرحباً',
  'welcome_message': 'مرحباً بك في وصال',
  'get_started': 'ابدأ الآن',
  'skip': 'تخطي',

  // Home
  'home': 'الرئيسية',
  'all_chats': 'جميع المحادثات',
  'all_groups': 'جميع المجموعات',
  'recent': 'الأخيرة',
  'no_results': 'لا توجد نتائج',

  // Status
  'status': 'الحالة',
  'my_status': 'حالتي',
  'add_status': 'إضافة حالة',
  'no_status': 'لا توجد تحديثات حالة',

  // Time
  'today': 'اليوم',
  'yesterday': 'أمس',
  'just_now': 'الآن',
  'minutes_ago': 'دقائق مضت',
  'hours_ago': 'ساعات مضت',

  // Confirmations
  'delete_chat': 'حذف المحادثة',
  'delete_chat_confirm': 'هل أنت متأكد من حذف هذه المحادثة؟',
  'clear_chat': 'مسح المحادثة',
  'clear_chat_confirm': 'هل أنت متأكد من مسح هذه المحادثة؟',
  'block_user': 'حظر المستخدم',
  'block_user_confirm': 'هل أنت متأكد من حظر هذا المستخدم؟',
  'unblock_user': 'إلغاء الحظر',

  // Search & Add Contact
  'cannot_add_yourself': 'لا يمكنك إضافة نفسك',
  'user_found': 'تم العثور على المستخدم بنجاح',
  'user_not_found': 'المستخدم غير موجود',
  'search_error': 'خطأ أثناء البحث',

  // Pinned Chats
  'pinned_chats': 'المحادثات المثبتة',
  'long_press_to_drag': 'اضغط مطولاً للسحب',

  // Archived Chats
  'archive': 'أرشفة',
  'unarchive': 'إلغاء الأرشفة',
  'archived_chats': 'المحادثات المؤرشفة',
  'no_archived_chats': 'لا توجد محادثات مؤرشفة',
  'archived_chats_hint': 'اسحب لليسار على المحادثة لأرشفتها',
  'chat_archived': 'تم أرشفة المحادثة',
  'chat_unarchived': 'تم إلغاء أرشفة المحادثة',

  // User Profile & Shared Media
  'media': 'الوسائط',
  'docs': 'المستندات',
  'links': 'الروابط',
  'message': 'رسالة',
  'call': 'اتصال',
  'report': 'إبلاغ',
  'no_shared_media': 'لا توجد وسائط مشتركة',
  'no_shared_audio': 'لا توجد رسائل صوتية مشتركة',
  'no_shared_docs': 'لا توجد مستندات مشتركة',
  'no_shared_links': 'لا توجد روابط مشتركة',
  'shared_media': 'الوسائط المشتركة',
  'view_profile': 'عرض الملف الشخصي',
};
