const Map<String, String> enUS = {
  // General
  'app_name': 'Wisaal',
  'ok': 'OK',
  'cancel': 'Cancel',
  'save': 'Save',
  'delete': 'Delete',
  'edit': 'Edit',
  'done': 'Done',
  'loading': 'Loading...',
  'error': 'Error',
  'success': 'Success',
  'warning': 'Warning',
  'yes': 'Yes',
  'no': 'No',
  'close': 'Close',
  'back': 'Back',
  'next': 'Next',
  'retry': 'Retry',
  'search': 'Search',
  'search_hint': 'Search...',

  // Theme
  'theme': 'Theme',
  'dark': 'Dark',
  'light': 'Light',
  'system': 'System',
  'dark_mode': 'Dark Mode',
  'light_mode': 'Light Mode',
  'system_mode': 'System Default',

  // Language
  'language': 'Language',
  'english': 'English',
  'arabic': 'Arabic',
  'select_language': 'Select Language',

  // Authentication
  'login': 'Login',
  'logout': 'Logout',
  'sign_up': 'Sign Up',
  'email': 'Email',
  'password': 'Password',
  'confirm_password': 'Confirm Password',
  'forgot_password': 'Forgot Password?',
  'reset_password': 'Reset Password',
  'create_account': 'Create Account',
  'already_have_account': 'Already have an account?',
  'dont_have_account': "Don't have an account?",
  'enter_email': 'Enter your email',
  'enter_password': 'Enter your password',
  'enter_name': 'Enter your name',
  'invalid_email': 'Invalid email address',
  'password_too_short': 'Password is too short',
  'passwords_not_match': 'Passwords do not match',
  'login_success': 'Login successful',
  'signup_success': 'Account created successfully',
  'logout_confirm': 'Are you sure you want to logout?',
  'email_verified': 'Your email has been verified!',
  'check_email': 'Please check your email',

  // Profile
  'profile': 'Profile',
  'edit_profile': 'Edit Profile',
  'name': 'Name',
  'username': 'Username',
  'bio': 'Bio',
  'phone': 'Phone',
  'change_photo': 'Change Photo',
  'update_profile': 'Update Profile',
  'profile_updated': 'Profile updated successfully',

  // Settings
  'settings': 'Settings',
  'general': 'General',
  'notifications': 'Notifications',
  'privacy': 'Privacy',
  'about': 'About',
  'help': 'Help',
  'appearance': 'Appearance',

  // Chat
  'chats': 'Chats',
  'messages': 'Messages',
  'new_message': 'New Message',
  'type_message': 'Type a message...',
  'send': 'Send',
  'delivered': 'Delivered',
  'read': 'Read',
  'online': 'Online',
  'offline': 'Offline',
  'typing': 'typing...',
  'last_seen': 'Last seen',
  'delete_message': 'Delete Message',
  'edit_message': 'Edit Message',
  'copy_message': 'Copy',
  'reply': 'Reply',
  'forward': 'Forward',
  'delete_for_me': 'Delete for me',
  'delete_for_everyone': 'Delete for everyone',
  'message_deleted': 'This message was deleted',
  'no_messages': 'No messages yet',
  'start_conversation': 'Start a conversation',
  'pin_message': 'Pin Message',
  'unpin_message': 'Unpin Message',
  'pinned_messages': 'Pinned Messages',

  // Contacts
  'contacts': 'Contacts',
  'add_contact': 'Add Contact',
  'new_contact': 'New Contact',
  'add_new_contact': 'Add a new friend',
  'search_contacts': 'Search contacts...',
  'contacts_on_app': 'Contacts on Wisaal',
  'no_contacts': 'No contacts yet',
  'invite_friends': 'Invite your friends to the app',
  'saved_contacts': 'Saved Contacts',
  'contact_saved': 'Contact saved',
  'contact_deleted': 'Contact deleted',
  'hey_there': 'Hey there!',
  'you': 'You',
  'user': 'User',
  'add': 'Add',
  'login_required': 'You must login first',

  // Groups
  'groups': 'Groups',
  'create_group': 'Create Group',
  'new_group': 'New Group',
  'create_new_group': 'Create a group with friends',
  'group_name': 'Group Name',
  'add_members': 'Add Members',
  'members': 'Members',
  'leave_group': 'Leave Group',
  'admin': 'Admin',
  'no_groups': 'No groups yet',

  // Calls
  'calls': 'Calls',
  'voice_call': 'Voice Call',
  'video_call': 'Video Call',
  'incoming_call': 'Incoming Call',
  'outgoing_call': 'Outgoing Call',
  'missed_call': 'Missed Call',
  'call_ended': 'Call Ended',
  'calling': 'Calling...',
  'no_calls': 'No calls yet',

  // Media
  'camera': 'Camera',
  'gallery': 'Gallery',
  'document': 'Document',
  'audio': 'Audio',
  'video': 'Video',
  'image': 'Image',
  'file': 'File',
  'location': 'Location',
  'share_location': 'Share Location',

  // Errors
  'connection_error': 'Connection error',
  'no_internet': 'No internet connection',
  'something_went_wrong': 'Something went wrong',
  'try_again': 'Please try again',
  'session_expired': 'Session expired',
  'permission_denied': 'Permission denied',

  // Welcome
  'welcome': 'Welcome',
  'welcome_message': 'Welcome to Wisaal',
  'get_started': 'Get Started',
  'skip': 'Skip',

  // Home
  'home': 'Home',
  'all_chats': 'All Chats',
  'all_groups': 'All Groups',
  'recent': 'Recent',
  'no_results': 'No results',

  // Status
  'status': 'Status',
  'my_status': 'My Status',
  'add_status': 'Add Status',
  'no_status': 'No status updates',

  // Time
  'today': 'Today',
  'yesterday': 'Yesterday',
  'just_now': 'Just now',
  'minutes_ago': 'minutes ago',
  'hours_ago': 'hours ago',

  // Confirmations
  'delete_chat': 'Delete Chat',
  'delete_chat_confirm': 'Are you sure you want to delete this chat?',
  'clear_chat': 'Clear Chat',
  'clear_chat_confirm': 'Are you sure you want to clear this chat?',
  'block_user': 'Block User',
  'block_user_confirm': 'Are you sure you want to block this user?',
  'unblock_user': 'Unblock User',

  // Search & Add Contact
  'cannot_add_yourself': 'You cannot add yourself',
  'user_found': 'User found successfully',
  'user_not_found': 'User not found',
  'search_error': 'Error while searching',

  // Pinned Chats
  'pinned_chats': 'Pinned Chats',
  'long_press_to_drag': 'Long press to drag',

  // Archived Chats
  'archive': 'Archive',
  'unarchive': 'Unarchive',
  'archived_chats': 'Archived Chats',
  'no_archived_chats': 'No archived chats',
  'archived_chats_hint': 'Swipe left on a chat to archive it',
  'chat_archived': 'Chat archived',
  'chat_unarchived': 'Chat unarchived',

  // User Profile & Shared Media
  'media': 'Media',
  'docs': 'Docs',
  'links': 'Links',
  'message': 'Message',
  'call': 'Call',
  'report': 'Report',
  'no_shared_media': 'No shared media',
  'no_shared_audio': 'No shared voice messages',
  'no_shared_docs': 'No shared documents',
  'no_shared_links': 'No shared links',
  'shared_media': 'Shared Media',
  'view_profile': 'View Profile',
};
