import 'package:flutter/material.dart';

const dBackgroundColor = Color(0xFF0A0E14);
const dSurfaceColor = Color(0xFF141A22);
const dPrimaryColor = Color(0xFF00BFA6);
const dSecondaryColor = Color(0xFF00E5CC);
const dContainerColor = Color(0xFF1E2630);
const donBackgroundColor = Color(0xFFF0F4F8);
const donContainerColor = Color(0xFF8B99A8);
const dSentBubbleColor = Color(0xFF00BFA6);
const dReceivedBubbleColor = Color(0xFF1E2630);
const dCardColor = Color(0xFF141A22);
const dDividerColor = Color(0xFF2A3441);
const dErrorColor = Color(0xFFFF6B6B);
const dSuccessColor = Color(0xFF4ADE80);
const dAccentColor = Color(0xFF38BDF8);

const lBackgroundColor = Color(0xFFF8FAFC);
const lSurfaceColor = Color(0xFFFFFFFF);
const lPrimaryColor = Color(0xFF0EA5E9);
const lSecondaryColor = Color(0xFF06B6D4);
const lContainerColor = Color(0xFFF1F5F9);
const lonBackgroundColor = Color(0xFF0F172A);
const lonContainerColor = Color(0xFF64748B);
const lSentBubbleColor = Color(0xFF0EA5E9);
const lReceivedBubbleColor = Color(0xFFE2E8F0);
const lCardColor = Color(0xFFFFFFFF);
const lDividerColor = Color(0xFFE2E8F0);
const lErrorColor = Color(0xFFEF4444);
const lSuccessColor = Color(0xFF22C55E);
const lAccentColor = Color(0xFF8B5CF6);
