import 'package:flutter/material.dart';
import 'package:wissal_app/config/colors.dart';

final lightThem = ThemeData(
  brightness: Brightness.light,
  useMaterial3: true,
  primaryColor: lPrimaryColor,
  scaffoldBackgroundColor: lBackgroundColor,
  cardColor: lCardColor,
  dividerColor: lDividerColor,
  colorScheme: const ColorScheme.light(
    primary: lPrimaryColor,
    onPrimary: Colors.white,
    surface: lSurfaceColor,
    onSurface: lonBackgroundColor,
    primaryContainer: lPrimaryColor,
    onPrimaryContainer: Colors.white,
    secondary: lSecondaryColor,
    onSecondary: Colors.white,
    error: lErrorColor,
    onError: Colors.white,
  ),
  appBarTheme: const AppBarTheme(
    backgroundColor: lPrimaryColor,
    foregroundColor: Colors.white,
    elevation: 0,
    centerTitle: true,
    iconTheme: IconThemeData(color: Colors.white),
    titleTextStyle: TextStyle(
      color: Colors.white,
      fontSize: 20,
      fontWeight: FontWeight.w600,
      fontFamily: 'Poppins',
    ),
  ),
  bottomNavigationBarTheme: const BottomNavigationBarThemeData(
    backgroundColor: lSurfaceColor,
    selectedItemColor: lPrimaryColor,
    unselectedItemColor: lonContainerColor,
    elevation: 8,
  ),
  floatingActionButtonTheme: const FloatingActionButtonThemeData(
    backgroundColor: lPrimaryColor,
    foregroundColor: Colors.white,
    elevation: 4,
  ),
  inputDecorationTheme: InputDecorationTheme(
    filled: true,
    fillColor: lContainerColor,
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: BorderSide.none,
    ),
    hintStyle: const TextStyle(color: lonContainerColor),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      fontSize: 32,
      color: lPrimaryColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w800,
    ),
    headlineMedium: TextStyle(
      fontSize: 28,
      color: lonBackgroundColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w600,
    ),
    headlineSmall: TextStyle(
      fontSize: 22,
      color: lonBackgroundColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w600,
    ),
    titleLarge: TextStyle(
      fontSize: 20,
      color: lonBackgroundColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w600,
    ),
    titleMedium: TextStyle(
      fontSize: 16,
      color: lonBackgroundColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w500,
    ),
    bodyLarge: TextStyle(
      fontSize: 16,
      color: lonBackgroundColor,
      fontFamily: 'Poppins',
    ),
    bodyMedium: TextStyle(
      fontSize: 14,
      color: lonBackgroundColor,
      fontFamily: 'Poppins',
    ),
    labelLarge: TextStyle(
      fontSize: 14,
      color: lonContainerColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w500,
    ),
    labelMedium: TextStyle(
      fontSize: 12,
      color: lonContainerColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w400,
    ),
    labelSmall: TextStyle(
      fontSize: 11,
      color: lonContainerColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w300,
    ),
  ),
);

final darktThem = ThemeData(
  brightness: Brightness.dark,
  useMaterial3: true,
  primaryColor: dPrimaryColor,
  scaffoldBackgroundColor: dBackgroundColor,
  cardColor: dCardColor,
  dividerColor: dDividerColor,
  colorScheme: const ColorScheme.dark(
    primary: dPrimaryColor,
    onPrimary: Colors.white,
    surface: dSurfaceColor,
    onSurface: donBackgroundColor,
    primaryContainer: dPrimaryColor,
    onPrimaryContainer: Colors.white,
    secondary: dSecondaryColor,
    onSecondary: Colors.white,
    error: dErrorColor,
    onError: Colors.white,
  ),
  appBarTheme: const AppBarTheme(
    backgroundColor: dSurfaceColor,
    foregroundColor: donBackgroundColor,
    elevation: 0,
    centerTitle: true,
    iconTheme: IconThemeData(color: donBackgroundColor),
    titleTextStyle: TextStyle(
      color: donBackgroundColor,
      fontSize: 20,
      fontWeight: FontWeight.w600,
      fontFamily: 'Poppins',
    ),
  ),
  bottomNavigationBarTheme: const BottomNavigationBarThemeData(
    backgroundColor: dSurfaceColor,
    selectedItemColor: dPrimaryColor,
    unselectedItemColor: donContainerColor,
    elevation: 8,
  ),
  floatingActionButtonTheme: const FloatingActionButtonThemeData(
    backgroundColor: dPrimaryColor,
    foregroundColor: Colors.white,
    elevation: 4,
  ),
  inputDecorationTheme: InputDecorationTheme(
    filled: true,
    fillColor: dContainerColor,
    border: OutlineInputBorder(
      borderRadius: BorderRadius.circular(16),
      borderSide: BorderSide.none,
    ),
    hintStyle: const TextStyle(color: donContainerColor),
  ),
  textTheme: const TextTheme(
    headlineLarge: TextStyle(
      fontSize: 32,
      color: dPrimaryColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w800,
    ),
    headlineMedium: TextStyle(
      fontSize: 28,
      color: donBackgroundColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w600,
    ),
    headlineSmall: TextStyle(
      fontSize: 22,
      color: donBackgroundColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w600,
    ),
    titleLarge: TextStyle(
      fontSize: 20,
      color: donBackgroundColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w600,
    ),
    titleMedium: TextStyle(
      fontSize: 16,
      color: donBackgroundColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w500,
    ),
    bodyLarge: TextStyle(
      fontSize: 16,
      color: donBackgroundColor,
      fontFamily: 'Poppins',
    ),
    bodyMedium: TextStyle(
      fontSize: 14,
      color: donBackgroundColor,
      fontFamily: 'Poppins',
    ),
    labelLarge: TextStyle(
      fontSize: 14,
      color: donContainerColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w500,
    ),
    labelMedium: TextStyle(
      fontSize: 12,
      color: donContainerColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w400,
    ),
    labelSmall: TextStyle(
      fontSize: 11,
      color: donContainerColor,
      fontFamily: 'Poppins',
      fontWeight: FontWeight.w300,
    ),
  ),
);
